# Generated by Django 5.1.1 on 2024-10-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=6)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('info', models.TextField(blank=True, null=True)),
                ('cats', models.ManyToManyField(to='main.category')),
            ],
        ),
    ]
