# Generated by Django 5.1.1 on 2024-10-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_created_at_student_first_p_student_second_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_p',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
